### ISSUE TITLE
Zoom level 125% ++ on Chrome, 1920x1080 screen res, Ubuntu 14.04 causes UI overlap

### ISSUE THREAD

**Issue by frizensami** [Skaty/nusmods#2]
![screenshot from 2016-04-06 17 29 26](https://cloud.githubusercontent.com/assets/5507069/14312079/3a26ad64-fc1d-11e5-853a-6a6d97ce3ea1.png)

Note that "Generate Timetable" and the "Add modules" bar overlap, this effect worsens at higher zoom levels.

**Comment by Skaty** [comment]
Marked as invalid. The problem lies with the select2 selection box, which forces itself to be of a certain minimum size.
